[flake8]
max-line-length = 88
exclude = [".git", "__pycache__", "__init__.py", ".mypy_cache", "migrations", ".pytest_cache", "venv", ".venv"]

[tool.isort]
profile = "black"
src_paths = ["assistant", "bot", "tasks", "timetable_scrapper"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
line_length = 88
group_by_package = true
skip_glob = "*/migrations/*,*/venv/*,*/.venv/*,*/__init__.py"
skip = ["migrations"]

[tool.black]
exclude = ".venv|venv|.git|__pycache__|__init__.py|.mypy_cache|.pytest_cache|migrations"
# skip-string-normalization = true
line_length = 88

