"""added students_groups.tg_channel

Revision ID: 78e459995458
Revises: 3c9149132801
Create Date: 2021-02-09 02:54:00.774060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78e459995458'
down_revision = '3c9149132801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students_groups', sa.Column('tg_channel', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students_groups', 'tg_channel')
    # ### end Alembic commands ###
