"""init users

Revision ID: 9940720af183
Revises: fd3251835b06
Create Date: 2020-11-25 23:40:05.185441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9940720af183'
down_revision = 'fd3251835b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students_groups', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('users', sa.Column('current_state', sa.String(), nullable=True))
    op.add_column('users', sa.Column('state_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'tg_username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tg_username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'state_data')
    op.drop_column('users', 'current_state')
    op.alter_column('students_groups', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
