"""init users

Revision ID: fd3251835b06
Revises: b56a1081ae27
Create Date: 2020-11-25 22:47:19.364976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd3251835b06'
down_revision = 'b56a1081ae27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('students_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'students_groups', ['students_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'students_group_id')
    # ### end Alembic commands ###
